matriz_banda.o: matriz_banda.hpp matriz_banda.cpp matrix_like.hpp matrix_exception.tcc
matrix_exception.o: matrix_exception.hpp matrix_exception.cpp 
	g++ -c matrix_exception.cpp
	g++ -c matriz_banda.cpp
