real_matrix.o: real_matrix.hpp real_matrix.cpp real_vector.cpp real_vector_iterator.cpp
	g++ -O2 -c real_matrix.cpp

funcion_matriz.o: funcion_matriz.hpp funcion_matriz.cpp factorizacion.cpp
	g++ -O2 -c funcion_matriz.cpp
