huffman.run: main_huffman.c huffman.h huffman.c quicksort.c quicksort.h tree.c tree.h queue.h queue.c
	gcc -g main_huffman.c huffman.c tree.c queue.c quicksort.c -o huffman.run -lm

img_multiprocess.run: img.multiprocess.c quicksort.c median.c pgm1.c
	gcc -g img.multiprocess.c quicksort.c -o img_multiprocess.run
